# Generated by Django 2.1.7 on 2019-03-30 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('pro_description', models.CharField(max_length=1000)),
                ('req_date', models.DateTimeField()),
            ],
        ),
    ]
