# Generated by Django 2.2.5 on 2019-10-01 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blank', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='clients',
        ),
    ]
